import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { TableModeProvider } from "@/components/table-mode-provider";
import { Providers } from "@/components/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Apply dark mode class
                const storedTheme = localStorage.getItem('theme');
                const theme = storedTheme === 'light' || storedTheme === 'dark' ? storedTheme : 'dark';
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                }
                // Apply table mode class
                const storedTableMode = localStorage.getItem('sd-table-mode');
                const tableMode = storedTableMode === 'normal' || storedTableMode === 'focus' ? storedTableMode : 'focus';
                if (tableMode === 'normal') {
                  document.documentElement.classList.add('sd-table-mode-normal');
                }
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <Providers>
            <TableModeProvider>{children}</TableModeProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
